# Generated by Django 3.2.23 on 2023-12-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingrediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ricetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descrizione', models.TextField(blank=True)),
                ('prezzo', models.PositiveIntegerField(blank=True, null=True)),
                ('tempo_preparazione', models.PositiveIntegerField(blank=True, null=True)),
                ('difficolta', models.CharField(blank=True, choices=[('facile', 'Facile'), ('medio', 'Medio'), ('difficile', 'Difficile')], max_length=20)),
                ('ingredienti', models.ManyToManyField(blank=True, related_name='ricette', to='ingrediente.Ingrediente')),
            ],
        ),
    ]
