# Generated by Django 3.2.23 on 2023-12-07 10:09

from django.db import migrations

def load_initial_data(apps, schema_editor):
    ricetta_model = apps.get_model('ricetta','Ricetta')
    ricetta_model.objects.create (
        pk=1,
        nome = "Ricetta Uno",
        descrizione = "Descrizione ricetta Uno",
        prezzo = 20,
        tempo_preparazione = 30,
        difficolta = "facile"
    )
    ricetta_model.objects.create (
        pk=2,
        nome = "Ricetta Due",
        descrizione = "Descrizione ricetta Due",
        prezzo = 10,
        tempo_preparazione = 15,
        difficolta = "medio"
    )
    ricetta_model.objects.create (
        pk=3,
        nome = "Ricetta Tre",
        descrizione = "Descrizione ricetta Tre",
        prezzo = 20,
        tempo_preparazione = 30,
        difficolta = "difficile"
    )
    ricetta_model.objects.create (
        pk=4,
        nome = "Ricetta Quattro",
        descrizione = "Descrizione ricetta Quattro",
        prezzo = 10,
        tempo_preparazione = 15,
        difficolta = "facile"
    )
    ricetta_model.objects.create (
        pk=5,
        nome = "Ricetta Cinque",
        descrizione = "Descrizione ricetta uno",
        prezzo = 20,
        tempo_preparazione = 30,
        difficolta = "medio"
    )
    ricetta_model.objects.create (
        pk=6,
        nome = "Ricetta Sei",
        descrizione = "Descrizione ricetta Sei",
        prezzo = 10,
        tempo_preparazione = 15,
        difficolta = "difficile"
    )
    ricetta_model.objects.create (
        pk=7,
        nome = "Ricetta Sette",
        descrizione = "Descrizione ricetta Sette",
        prezzo = 20,
        tempo_preparazione = 30,
        difficolta = "facile"
    )
    ricetta_model.objects.create (
        pk=8,
        nome = "Ricetta Otto",
        descrizione = "Descrizione ricetta Otto",
        prezzo = 10,
        tempo_preparazione = 15,
        difficolta = "medio"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('ricetta', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
