# Generated by Django 3.2.23 on 2023-12-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ricetta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ristorante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('indirizzo', models.CharField(max_length=200)),
                ('proprietario', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('ricette', models.ManyToManyField(blank=True, related_name='ristoranti', to='ricetta.Ricetta')),
            ],
        ),
    ]
