# Generated by Django 3.2.23 on 2023-12-07 10:09

from django.db import migrations

def load_initial_data(apps, schema_editor):
    ristorante_model = apps.get_model('ristorante','Ristorante')
    ristorante_model.objects.create (
        pk=1,
        nome="ristorante Uno",
        indirizzo= "Via Roma 123",
        proprietario= "Mario Uno",
        email="mario@ristoranteuno.com"
    )
    ristorante_model.objects.create (
        pk=2,
        nome="ristorante Due",
        indirizzo= "Via Bologna 123",
        proprietario= "Mario Due",
        email="mario@ristorantedue.com"
    )
    ristorante_model.objects.create (
        pk=3,
        nome="ristorante Tre",
        indirizzo= "Via Milano 123",
        proprietario= "Mario Tre",
        email="mario@ristorantetre.com"
    )
    ristorante_model.objects.create (
        pk=4,
        nome="ristorante Quattro",
        indirizzo= "Via Torino 123",
        proprietario= "Mario Quattro",
        email="mario@ristorantequattro.com"
    )
    ristorante_model.objects.create (
        pk=5,
        nome="ristorante Cinque",
        indirizzo= "Via Napoli 123",
        proprietario= "Mario Cinque",
        email="mario@ristorantecinque.com"
    )
class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
