# Generated by Django 3.2.23 on 2023-12-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('unita_misura', models.CharField(blank=True, max_length=50)),
                ('quantita', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
