# Generated by Django 3.2.23 on 2023-12-07 10:09

from django.db import migrations

def load_initial_data(apps, schema_editor):
    ingrediente_model = apps.get_model('ingrediente','Ingrediente')
    ingrediente_model.objects.create (
        pk=1,
        nome="Ingrediente Uno",
        unita_misura= "g",
        quantita= 500
    )
    ingrediente_model.objects.create (
        pk=2,
        nome="Ingrediente Due",
        unita_misura= "g",
        quantita= 250
    )
    ingrediente_model.objects.create (
        pk=3,
        nome="Ingrediente Tre",
        unita_misura= "g",
        quantita= 125
    )
    ingrediente_model.objects.create (
        pk=4,
        nome="Ingrediente Quattro",
        unita_misura= "g",
        quantita= 60
    )
    ingrediente_model.objects.create (
        pk=5,
        nome="Ingrediente Cinque",
        unita_misura= "g",
        quantita= 30
    )
class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
